import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext({
  language: 'en',
  toggleLanguage: () => {},
  t: (key) => key,
});

const TRANSLATIONS = {
  en: {
    // Navbar
    home: "Home",
    dashboard: "Dashboard",
    chat: "🤖 Chat",
    aiCenter: "🛠️ AI Center",
    bazaar: "🛒 Bazaar",
    community: "👥 Community",
    weather: "☀️ Weather",
    mandiPrices: "📈 Mandi Prices",
    login: "Login",
    register: "Register",
    logout: "Logout",
    hi: "Hi",
    installApp: "📲 Install App",

    // Common Button/Status
    loading: "Loading...",
    submit: "Submit",
    error: "Error",
    success: "Success",

    // Home Page
    heroTitle: "Digital Agriculture Companion",
    heroSubtitle: "Smart Kisan bridges traditional wisdom with modern AI. Leverage crop simulators, visual disease diagnostics, and trading pipelines to maximize your farm's potential.",
    trustedFarmers: "🌾 Trusted by 15,000+ Farmers",
    getStarted: "Get Started Free 🚀",
    loginCta: "Log In",
    downloadApp: "📲 Download App",
    impactFarmers: "Registered Farmers",
    impactAccuracy: "Diagnosis Accuracy",
    impactTraded: "Harvest Traded",
    impactFees: "Commission Fees",
    featureTitle: "Everything a Farmer Needs 🌱",
    featureSubtitle: "One platform, all your farming needs covered.",
    pwaCTA: "📱 Take Smart Kisan Everywhere",
    pwaDesc: "Install Smart Kisan as a native app on your device. Works offline, loads instantly, no app store needed!",
    pwaStep1Title: "Tap Install App",
    pwaStep1Desc: "Click the button below",
    pwaStep2Title: "Confirm Install",
    pwaStep2Desc: "Browser shows a prompt",
    pwaStep3Title: "Launch from Home Screen",
    pwaStep3Desc: "Opens like a native app!",
    downloadFree: "📲 Download App — Free",
    installedSuccess: "✅ Smart Kisan is installed on your device!",

    // Interactive Crop Planner
    cropPlanner: "🌱 Interactive Crop Planner",
    cropPlannerDesc: "Select a crop and sowing date to preview your growth schedule!",
    selectCrop: "Select Crop",
    sowingDate: "Estimated Sowing Date",
    simulateButton: "Simulate Growth Timeline 📈",
    pipelinePreview: "Growth Pipeline Preview",
    pipelineConfigureDesc: "Configure parameters on the left and simulate to view growth steps.",
    milestonesTitle: "Sowing Milestones:",
    enterCustomCrop: "Enter Custom Crop Name",

    // Login Page
    welcomeBack: "Welcome Back",
    loginSubtitle: "Log in to manage your fields and access agricultural insights.",
    emailAddress: "Email Address",
    password: "Password",
    forgotPassword: "Forgot Password?",
    loginButton: "Log In Securely 🚀",
    newToKisan: "New to Smart Kisan?",
    createAccountLink: "Create an account",
    demoLogins: "🔑 Quick Trial demo logins",
    demoFarmer: "🌾 Demo Farmer",
    demoMerchant: "🛒 Demo Merchant",
    singleClickLogin: "Single-click login",
    resetPassword: "Reset Password",
    resetSubtitle: "Enter your email address to request a password reset verification code.",
    sendOTP: "Send Verification OTP 🔑",
    backToLogin: "Back to Login",
    newPasswordWizard: "New Password Wizard",
    resetCodeLabel: "6-Digit Reset Code (OTP)",
    enterNewPassword: "Enter New Password",
    submitNewPassword: "Submit & Reset Password 🔐",
    requestNewResetCode: "Request New Reset Code",
    minCharacters: "Minimum 6 characters",

    // Register Page
    createAccount: "Create Account",
    registerSubtitle: "Register to set up your agricultural dashboard profile.",
    selectUserRole: "Select User Role",
    farmerRole: "Farmer",
    farmerDesc: "Cultivate & Sell",
    merchantRole: "Merchant",
    merchantDesc: "Trade & Purchase",
    fullName: "Full Name",
    registerBtn: "Register & Start Dashboard 🚀",
    alreadyHaveAccount: "Already have an account?",

    // Crop Recommendations
    recommendationTitle: "AI Crop Recommendation Engine",
    recommendationSubtitle: "Input your soil properties and location parameters to predict optimal crop varieties and resource allocation.",
    soilLocationDetails: "🧪 Soil & Location Details",
    soilType: "Soil Type",
    soilLoamy: "Loamy Soil",
    soilSandy: "Sandy Soil",
    soilClay: "Clayey Soil",
    soilBlack: "Black Soil",
    soilRed: "Red Soil",
    season: "Season",
    seasonKharif: "Kharif (Monsoon)",
    seasonRabi: "Rabi (Winter)",
    seasonZaid: "Zaid (Summer)",
    regionState: "Region / State",
    gpsDetectBtn: "📍 GPS",
    irrigationLabel: "Irrigation/Water Supply Available",
    soilChemistry: "⚙️ Soil Chemistry (NPK & pH)",
    soilPH: "Soil pH",
    acidic: "Acidic (4.0)",
    neutral: "Neutral (7.0)",
    alkaline: "Alkaline (9.0)",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    generateRecommendations: "Generate AI Recommendations",
    detectedWeather: "Detected Location & Weather",
    matchPercentage: "Match",
    estProfit: "Est. Profit",
    estProfitLabel: "Est. Profit",
    yieldLabel: "Yield:",
    waterLabel: "Water:",
    demandLabel: "Demand:",
    fertilizerActionPlan: "Fertilizer & Action Plan for",
    stepCalendar: "Step-by-Step Calendar",

    // AI Center / Diagnostics
    agriCenterTitle: "AI Agri-Center",
    agriCenterSubtitle: "Access cutting-edge advisory tools including visual disease checking, water managers, soil NPK prescription tools, and dynamic crop planners.",
    leafDiagnostics: "Leaf Disease Diagnostics",
    leafDiagnosticsDesc: "Snap or upload a photo of the affected plant leaf. Our AI model examines textures and spotting to suggest treatments.",
    cropTypeHint: "Crop Type Hint",
    dragDropPhoto: "Click here or drag-and-drop crop photo",
    supportsFormats: "Supports PNG, JPG, JPEG",
    analyzeImageBtn: "Analyze Image 🔬",
    diagnosticsReport: "AI Diagnostic Report",
    printPrescription: "🖨️ Print Prescription",
    uploadPrompt: "Upload a leaf photo and click analyze to output report.",
    modelConfidence: "AI Model Confidence",
    basedOnFoliage: "Based on visual foliage index patterns",
    cropTarget: "Crop Target:",
    detectedDisease: "Detected Disease:",
    severityLevel: "Threat Severity Level:",
    severityThreat: "Severity Threat",
    healthyLeafRef: "Reference Healthy Leaf:",
    organicRemedy: "Organic Remedy (Recommended)",
    chemicalControl: "Chemical Control",
    organicPrescription: "Organic Prescription:",
    chemicalGuidelines: "Chemical Treatment Guidelines:",

    // Kisan Bazaar
    bazaarTitle: "Kisan Bazaar",
    bazaarSubtitle: "Trade premium seeds, specialized tools, bio-fertilizers, or sell your own farm harvest directly to other farmers and wholesale merchants.",
    onlineSellTitle: "Sell Your Crop Online",
    onlineSellDesc: "List your crop, quality grade, asking price, and contact details to sell directly to verified wholesale buyers.",
    bazaarSellerCenter: "🚜 Seller Center",
    bazaarBrowse: "🛒 Browse Bazaar",
    bazaarCart: "🛒 Cart",
    bazaarFilterCategory: "Filter by Category",
    bazaarSearchPlaceholder: "Search products, categories, sellers...",
    bazaarSortPopularity: "Popularity",
    bazaarSortRating: "Highest Rated",
    bazaarSortPriceLow: "Price: Low to High",
    bazaarSortPriceHigh: "Price: High to Low",
    bazaarListSurplus: "📢 List Surplus to Sell",
    bazaarCloseForm: "Close Listing Form ✖",
    bazaarLoginToSell: "🔐 Login to sell your items",
    bazaarListHarvestTitle: "List Your Agriculture Item",
    bazaarListHarvestDesc: "Set your wholesale pricing, select category, upload or choose an image, and submit. Your listing appears instantly in the Bazaar catalog.",
    bazaarItemName: "Item / Crop Name *",
    bazaarCategory: "Category",
    bazaarSaleUnit: "Sale Unit *",
    bazaarWholesalePrice: "Wholesale Price (₹) *",
    bazaarSeedsGermination: "Germination Rate (%)",
    bazaarFertilizersRatio: "NPK Formula Ratio",
    bazaarProduceHarvestDate: "Harvest Date",
    bazaarItemDesc: "Item Description",
    bazaarPhotoPreset: "Choose Photo Preset (Or enter URL below)",
    bazaarPublishListing: "Publish Listing in Bazaar 🚀",
    bazaarPublishing: "Publishing listing...",
    bazaarLoadingInventory: "Loading Bazaar Inventory...",
    bazaarNoProductsMatched: "No products matched your filters.",
    bazaarTryClearing: "Try clearing search queries or checking other categories.",
    bazaarFarmerDirect: "👨‍🌾 Farmer Direct",
    bazaarMandiRef: "Mandi Ref",
    bazaarAddToCart: "+ Add 🛒",
    bazaarActiveListings: "Active Listings",
    bazaarAvailableItems: "Available Items",
    bazaarEstValue: "Est. Value (25 units sold)",
    bazaarOrderSuccessful: "Order placed successfully! Verified by Kisan SMS network.",
    bazaarCheckoutBtn: "Proceed to Checkout",
    bazaarOrderPlaced: "Order Placed!",
    bazaarOrderId: "Order ID:",
    bazaarCartEmpty: "Your cart is empty.",
    bazaarCloseBtn: "Close",

    // Mandi Prices
    mandiTitle: "Live Mandi Prices",
    mandiSubtitle: "Real-time agricultural commodity prices from 15+ APMC mandis across India.",
    pwaAndroidHint: "Android Chrome: Menu → 'Add to Home screen'",
    mandiSearchPlaceholder: "Search crop...",
    mandiAllCommodities: "All Commodities",
    mandiMinPrice: "Min Price",
    mandiAvgPrice: "Avg Price",
    mandiMaxPrice: "Max Price",
    mandiPriceSpread: "Price Spread",
    mandiTotalArrivals: "Total Arrivals",
    mandiTrend: "30-Day Trend",
    mandiBestBuy: "Best Buy Mandi",
    mandiBestSell: "Best Sell Mandi",
    mandiAutoRefresh: "Auto Refresh",
    mandiLastUpdate: "Last Update",
    mandiRefreshBtn: "🔄 Refresh",
    mandiWatchBtn: "☆ Watch",
    mandiWatchingBtn: "⭐ Watching",
    mandiSortLabel: "Sort By:",
    mandiArrivalTons: "Arrivals (Tons)",
    mandiMspBannerTitle: "Minimum Support Price (MSP)",
    mandiMspBannerDesc: "Government guaranteed MSP. If market prices fall below MSP, sell to government procurement agencies to protect your income.",
    mandiForecastTitle: "📊 Price Prediction Forecast (Next 7-30 Days)",
    mandiForecastDesc: "AI-powered commodity arrivals analysis and regional weather correlation.",
    mandiForecastSelect: "Forecast Period",
    mandiForecastBtn: "Analyze Forecast Trend 🔍",
    mandiForecastResult: "Prediction Result",
    mandiForecastSentiment: "Market Sentiment:",
    mandiForecastAdvise: "Actionable Advisory:",
    mandiForecastExpected: "Expected Price Range:",

    // Community Forum / Resources Hub
    communityResourcesTitle: "Community Resource Center & Advisories",
    communityResourcesSubtitle: "Community Advisory Board & Officer Directory",
    communityDirectoryTitle: "District Agronomist & Officer Directory",
    communityOfficerName: "Name",
    communityOfficerRole: "Designation / Role",
    communityOfficerContact: "Contact Number",
    communityOfficerRegion: "District / Region",
    communityMeetingsTitle: "📅 Upcoming Community Training & Webinars",
    communityMeetingsDesc: "Participate in live agricultural sessions hosted by agronomists.",
    communityMeetingTitle: "Topic",
    communityMeetingDate: "Date & Time",
    communityMeetingLink: "Action",
    communityMeetingJoin: "Join Session 🎥",
    communitySchemesTitle: "🏛️ Useful Government Portals & Crop Insurance Schemes",
    communitySchemesDesc: "Direct links to support and subsidy portals."
  },
  mr: {
    // Navbar
    home: "मुख्यपृष्ठ",
    dashboard: "डॅशबोर्ड",
    chat: "🤖 गप्पा",
    aiCenter: "🛠️ कृषी केंद्र",
    bazaar: "🛒 बाजार",
    community: "👥 समुदाय",
    weather: "☀️ हवामान",
    mandiPrices: "📈 बाजार भाव",
    login: "लॉगिन",
    register: "नोंदणी",
    logout: "बाहेर पडा",
    hi: "नमस्कार",
    installApp: "📲 ॲप डाउनलोड करा",

    // Common Button/Status
    loading: "लोड होत आहे...",
    submit: "सबमिट करा",
    error: "त्रुटी",
    success: "यशस्वी",

    // Home Page
    heroTitle: "डिजिटल कृषी साथीदार",
    heroSubtitle: "स्मार्ट किसान पारंपारिक ज्ञान आणि आधुनिक कृत्रिम बुद्धिमत्ता (AI) जोडतो. पीक सिम्युलेटर, रोग तपासणी आणि व्यापारी माध्यमांचा वापर करून नफा वाढवा.",
    trustedFarmers: "🌾 १५,०००+ शेतकऱ्यांचा विश्वास",
    getStarted: "विनामूल्य सुरू करा 🚀",
    loginCta: "लॉगिन करा",
    downloadApp: "📲 ॲप डाउनलोड करा",
    impactFarmers: "नोंदणीकृत शेतकरी",
    impactAccuracy: "निदान अचूकता",
    impactTraded: "व्यापार झालेले पीक",
    impactFees: "मध्यस्थी शुल्क",
    featureTitle: "शेतकऱ्यांच्या गरजेच्या सर्व गोष्टी 🌱",
    featureSubtitle: "एकच व्यासपीठ, तुमच्या सर्व गरजा पूर्ण करणारे.",
    pwaCTA: "📱 स्मार्ट किसान सर्वत्र न्या",
    pwaDesc: "स्मार्ट किसान ॲप तुमच्या मोबाईल डिव्हाइसवर डाउनलोड करा. ऑफलाइन वापरता येते आणि त्वरित उघडते!",
    pwaStep1Title: "ॲप डाउनलोड करा वर क्लिक करा",
    pwaStep1Desc: "खालील बटणावर क्लिक करा",
    pwaStep2Title: "डाउनलोडची पुष्टी करा",
    pwaStep2Desc: "ब्राउझरवर सूचना येईल",
    pwaStep3Title: "होम स्क्रीनवरून सुरू करा",
    pwaStep3Desc: "नेटीव्ह ॲपसारखे उघडेल!",
    downloadFree: "📲 ॲप डाउनलोड करा — विनामूल्य",
    installedSuccess: "✅ स्मार्ट किसान तुमच्या डिव्हाइसवर स्थापित आहे!",

    // Interactive Crop Planner
    cropPlanner: "🌱 परस्परसंवादी पीक नियोजक",
    cropPlannerDesc: "तुमच्या पीक वाढीचे वेळापत्रक पाहण्यासाठी पीक आणि पेरणीची तारीख निवडा!",
    selectCrop: "पीक निवडा",
    sowingDate: "पेरणीची अंदाजे तारीख",
    simulateButton: "वाढीचे वेळापत्रक पहा 📈",
    pipelinePreview: "पीक वाढीचे वेळापत्रक",
    pipelineConfigureDesc: "डावीकडील माहिती निवडून वेळापत्रक तयार करा.",
    milestonesTitle: "पेरणीचे टप्पे:",
    enterCustomCrop: "पिकाचे नाव टाका",

    // Login Page
    welcomeBack: "पुन्हा स्वागत आहे",
    loginSubtitle: "तुमची शेती व्यवस्थापित करण्यासाठी आणि कृषी माहिती मिळवण्यासाठी लॉगिन करा.",
    emailAddress: "ईमेल पत्ता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड विसरलात?",
    loginButton: "सुरक्षित लॉगिन 🚀",
    newToKisan: "स्मार्ट किसानवर नवीन आहात?",
    createAccountLink: "नवीन खाते तयार करा",
    demoLogins: "🔑 चाचणी लॉगिन (Demo Logins)",
    demoFarmer: "🌾 शेतकरी लॉगिन (Demo)",
    demoMerchant: "🛒 व्यापारी लॉगिन (Demo)",
    singleClickLogin: "एक-क्लिक लॉगिन",
    resetPassword: "पासवर्ड रिसेट करा",
    resetSubtitle: "व्हेरिफिकेशन कोड (OTP) मिळवण्यासाठी तुमचा नोंदणीकृत ईमेल टाका.",
    sendOTP: "व्हेरिफिकेशन कोड (OTP) पाठवा 🔑",
    backToLogin: "लॉगिनवर जा",
    newPasswordWizard: "नवीन पासवर्ड तयार करा",
    resetCodeLabel: "६-अंकी रिसेट कोड (OTP)",
    enterNewPassword: "नवीन पासवर्ड टाका",
    submitNewPassword: "पासवर्ड बदला आणि सबमिट करा 🔐",
    requestNewResetCode: "नवीन रिसेट कोड मागवा",
    minCharacters: "किमान ६ अक्षरे",

    // Register Page
    createAccount: "खाते तयार करा",
    registerSubtitle: "तुमचा कृषी डॅशबोर्ड प्रोफाइल तयार करण्यासाठी नोंदणी करा.",
    selectUserRole: "वापरकर्ता भूमिका निवडा",
    farmerRole: "शेतकरी",
    farmerDesc: "लागवड आणि विक्री",
    merchantRole: "व्यापारी",
    merchantDesc: "खरेदी आणि व्यापार",
    fullName: "पूर्ण नाव",
    registerBtn: "नोंदणी करा आणि डॅशबोर्ड सुरू करा 🚀",
    alreadyHaveAccount: "आधीच खाते आहे का?",

    // Crop Recommendations
    recommendationTitle: "AI पीक शिफारस यंत्रणा",
    recommendationSubtitle: "तुमच्या शेतीसाठी योग्य पीक आणि संसाधनांचे नियोजन करण्यासाठी जमीन आणि हवामानाची माहिती टाका.",
    soilLocationDetails: "🧪 माती आणि ठिकाणाचे तपशील",
    soilType: "मातीचा प्रकार",
    soilLoamy: "गाळाची/लोमी माती",
    soilSandy: "वाळूमय माती",
    soilClay: "चिकणमाती",
    soilBlack: "काळी कसदार माती",
    soilRed: "तांबडी माती",
    season: "हंगाम",
    seasonKharif: "खरीप (पावसाळी)",
    seasonRabi: "रब्बी (हिवाळी)",
    seasonZaid: "उन्हाळी (उन्हाळी)",
    regionState: "प्रदेश / राज्य",
    gpsDetectBtn: "📍 जीपीएस",
    irrigationLabel: "सिंचन/पाण्याची उपलब्धता आहे",
    soilChemistry: "⚙️ मातीतील घटक (NPK आणि pH)",
    soilPH: "मातीचा पीएच (pH)",
    acidic: "आम्लधर्मी (4.0)",
    neutral: "उदासीन (7.0)",
    alkaline: "अल्कलीधर्मी (9.0)",
    nitrogen: "नायट्रोजन (N)",
    phosphorus: "फॉस्फरस (P)",
    potassium: "पोटॅश (K)",
    generateRecommendations: "पीक शिफारसी मिळवा",
    detectedWeather: "शोधलेले ठिकाण आणि हवामान",
    matchPercentage: "जुळणारे",
    estProfit: "अंदाजे नफा",
    estProfitLabel: "अंदाजे नफा",
    yieldLabel: "उत्पादन:",
    waterLabel: "पाणी:",
    demandLabel: "मागणी:",
    fertilizerActionPlan: "खत आणि कृती योजना:",
    stepCalendar: "टप्प्याटप्प्याने दिनदर्शिका",

    // AI Center / Diagnostics
    agriCenterTitle: "कृषी एआय केंद्र",
    agriCenterSubtitle: "पीक रोग तपासणी, पाणी व्यवस्थापन, मातीचे NPK खत नियोजन आणि पीक नियोजक यांसारख्या आधुनिक साधनांचा वापर करा.",
    leafDiagnostics: "पीक रोग निदान",
    leafDiagnosticsDesc: "पिकाच्या रोगाचे निदान करण्यासाठी रोगट पानाचा फोटो अपलोड करा. आमचे एआय मॉडेल लगेच उपाय सुचवेल.",
    cropTypeHint: "पिकाचा प्रकार",
    dragDropPhoto: "फोटो निवडा किंवा ड्रॅग करा",
    supportsFormats: "फक्त PNG, JPG, JPEG फॉरमॅट चालतील",
    analyzeImageBtn: "तपासा आणि निदान करा 🔬",
    diagnosticsReport: "एआय रोग निदान अहवाल",
    printPrescription: "🖨️ शिफारसी प्रिंट करा",
    uploadPrompt: "रोग निदान पाहण्यासाठी पानाचा फोटो अपलोड करा.",
    modelConfidence: "एआय मॉडेलची अचूकता",
    basedOnFoliage: "पानाच्या विविध घटकांच्या विश्लेषणावर आधारित",
    cropTarget: "निवडलेले पीक:",
    detectedDisease: "शोधलेला रोग:",
    severityLevel: "रोगाची तीव्रता:",
    severityThreat: "रोगाचा धोका",
    healthyLeafRef: "निरोगी पानाचा संदर्भ:",
    organicRemedy: "सेंद्रिय उपाय (शिफारस केलेले)",
    chemicalControl: "रासायनिक नियंत्रण",
    organicPrescription: "सेंद्रिय उपाय:",
    chemicalGuidelines: "रासायनिक उपचार मार्गदर्शक तत्वे:",

    // Kisan Bazaar
    bazaarTitle: "किसान बाजार",
    bazaarSubtitle: "उत्कृष्ट बियाणे, शेतीची साधने, जैविक खते खरेदी करा किंवा तुमचे स्वतःचे पीक थेट इतर शेतकऱ्यांना आणि व्यापाऱ्यांना विकून नफा मिळवा.",
    onlineSellTitle: "तुमचे पीक ऑनलाईन विका",
    onlineSellDesc: "तुमचे पीक, त्याची प्रत, किंमत आणि संपर्क तपशील टाकून थेट ऑनलाईन खरेदीदारांशी संपर्क साधा आणि माल विका.",
    bazaarSellerCenter: "🚜 विक्रेता केंद्र",
    bazaarBrowse: "🛒 बाजार पहा",
    bazaarCart: "🛒 कार्ट",
    bazaarFilterCategory: "श्रेणीनुसार फिल्टर करा",
    bazaarSearchPlaceholder: "उत्पादने, श्रेणी, विक्रेते शोधा...",
    bazaarSortPopularity: "लोकप्रियता",
    bazaarSortRating: "उच्च मानांकित",
    bazaarSortPriceLow: "किंमत: कमी ते जास्त",
    bazaarSortPriceHigh: "किंमत: जास्त ते कमी",
    bazaarListSurplus: "📢 पीक विक्रीसाठी नोंदवा",
    bazaarCloseForm: "फॉर्म बंद करा ✖",
    bazaarLoginToSell: "🔐 विक्री करण्यासाठी आधी लॉगिन करा",
    bazaarListHarvestTitle: "तुमच्या पिकाची/वस्तूची नोंदणी करा",
    bazaarListHarvestDesc: "तुमची घाऊक किंमत ठरवा, श्रेणी निवडा, फोटो अपलोड करा आणि सबमिट करा. तुमची नोंदणी बाजारात त्वरित दिसून येईल.",
    bazaarItemName: "वस्तू किंवा पिकाचे नाव *",
    bazaarCategory: "श्रेणी",
    bazaarSaleUnit: "विक्रीचे युनिट *",
    bazaarWholesalePrice: "घाऊक किंमत (₹) *",
    bazaarSeedsGermination: "बियाणे उगवण क्षमता (%)",
    bazaarFertilizersRatio: "NPK खत प्रमाण",
    bazaarProduceHarvestDate: "काढणीची तारीख",
    bazaarItemDesc: "वस्तूचे वर्णन",
    bazaarPhotoPreset: "फोटो निवडा (किंवा खाली URL टाका)",
    bazaarPublishListing: "बाझारमध्ये नोंदणी प्रकाशित करा 🚀",
    bazaarPublishing: "प्रकाशित होत आहे...",
    bazaarLoadingInventory: "बाजार यादी लोड होत आहे...",
    bazaarNoProductsMatched: "तुमच्या फिल्टरशी जुळणारे उत्पादन सापडले नाही.",
    bazaarTryClearing: "शोध संज्ञा बदला किंवा इतर श्रेणी तपासा.",
    bazaarFarmerDirect: "👨‍🌾 थेट शेतकरी",
    bazaarMandiRef: "बाजार भाव संदर्भ",
    bazaarAddToCart: "+ कार्टमध्ये जोडा 🛒",
    bazaarActiveListings: "सक्रिय यादी",
    bazaarAvailableItems: "उपलब्ध वस्तू",
    bazaarEstValue: "अंदाजे मूल्य (२५ युनिट्स विक्री)",
    bazaarOrderSuccessful: "ऑर्डर यशस्वीरित्या नोंदवली गेली! किसान एसएमएस नेटवर्कद्वारे व्हेरिफाय केली जाईल.",
    bazaarCheckoutBtn: "चेकआउट करा",
    bazaarOrderPlaced: "ऑर्डर पूर्ण झाली!",
    bazaarOrderId: "ऑर्डर आयडी:",
    bazaarCartEmpty: "तुमची कार्ट रिकामी आहे.",
    bazaarCloseBtn: "बंद करा",

    // Mandi Prices
    mandiTitle: "बाजार भाव",
    mandiSubtitle: "भारतातील १५+ कृषी उत्पन्न बाजार समित्यांमधील पिकांचे चालू बाजार भाव.",
    pwaAndroidHint: "अँड्रॉइड क्रोम: मेनू → 'होम स्क्रीनवर जोडा'",
    mandiSearchPlaceholder: "पीक शोधा...",
    mandiAllCommodities: "सर्व पिके",
    mandiMinPrice: "किमान किंमत",
    mandiAvgPrice: "अंदाजे किंमत",
    mandiMaxPrice: "कमाल किंमत",
    mandiPriceSpread: "किंमतीतील फरक",
    mandiTotalArrivals: "एकूण आवक",
    mandiTrend: "३०-दिवसांचा कल",
    mandiBestBuy: "स्वस्त खरेदी बाजार",
    mandiBestSell: "महाग विक्री बाजार",
    mandiAutoRefresh: "स्वयंचलित रीफ्रेश",
    mandiLastUpdate: "शेवटचे अपडेट",
    mandiRefreshBtn: "🔄 रीफ्रेश",
    mandiWatchBtn: "☆ वॉचलिस्ट",
    mandiWatchingBtn: "⭐ वॉचिंग",
    mandiSortLabel: "क्रमवारी लावा:",
    mandiArrivalTons: "आवक (टन)",
    mandiMspBannerTitle: "किमान आधारभूत किंमत (MSP)",
    mandiMspBannerDesc: "शासकीय आधारभूत हमीभाव. जर बाजारातील भाव हमीभावापेक्षा कमी असतील, तर संरक्षण मिळवण्यासाठी शासकीय खरेदी केंद्रांवर विक्री करा.",
    mandiForecastTitle: "📊 भावी बाजार भाव अंदाज (पुढील ७-३० दिवस)",
    mandiForecastDesc: "AI द्वारे पिकाची आवक आणि हवामानाचा अंदाज घेऊन बनवलेले विश्लेषण.",
    mandiForecastSelect: "अंदाजाचा कालावधी",
    mandiForecastBtn: "बाजार भाव अंदाज तपासा 🔍",
    mandiForecastResult: "अंदाजाचे निकाल",
    mandiForecastSentiment: "बाजार कल (Sentiment):",
    mandiForecastAdvise: "कृती सल्ला (Advisory):",
    mandiForecastExpected: "अपेक्षित बाजार भाव श्रेणी:",

    // Community Forum / Resources Hub
    communityResourcesTitle: "कृषी समुदाय संसाधन केंद्र व सल्ला",
    communityResourcesSubtitle: "सामुदायिक सल्लागार मंडळ आणि अधिकारी डिरेक्टरी",
    communityDirectoryTitle: "जिल्हा कृषी अधिकारी व सल्लागार डिरेक्टरी",
    communityOfficerName: "नाव",
    communityOfficerRole: "पद / भूमिका",
    communityOfficerContact: "संपर्क क्रमांक",
    communityOfficerRegion: "जिल्हा / तालुका",
    communityMeetingsTitle: "📅 आगामी शेतकरी प्रशिक्षण आणि वेबिनार वेळापत्रक",
    communityMeetingsDesc: "तज्ज्ञ कृषी अधिकाऱ्यांनी आयोजित केलेल्या थेट सत्रांमध्ये सहभागी व्हा.",
    communityMeetingTitle: "विषय",
    communityMeetingDate: "दिनांक आणि वेळ",
    communityMeetingLink: "कृती",
    communityMeetingJoin: "सत्रामध्ये सहभागी व्हा 🎥",
    communitySchemesTitle: "🏛️ उपयुक्त सरकारी योजना व पीक विमा पोर्टल्स",
    communitySchemesDesc: "थेट सरकारी मदत आणि अनुदान योजनांच्या लिंक्स."
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('sk-lang');
    return saved === 'mr' ? 'mr' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('sk-lang', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'mr' : 'en'));
  };

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;
