import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext({
  language: 'en',
  toggleLanguage: () => {},
  setLanguage: () => {},
  t: (key) => key,
});

const TRANSLATIONS = {
  en: {
    // Navbar
    title: "Smart Kisan",
    home: "Home",
    dashboard: "Dashboard",
    chat: "🤖 Chat",
    aiCenter: "🛠️ AI Center",
    bazaar: "🛒 Bazaar",
    community: "👥 Community",
    weather: "☀️ Weather",
    mandiPrices: "📈 Mandi Prices",
    recommendations: "🌱 Crop Advisor",
    learning: "📚 Learning Hub",
    login: "Login",
    register: "Register",
    logout: "Logout",
    hi: "Hi",
    installApp: "📲 Install App",

    // Common Button/Status
    loading: "Loading...",
    submit: "Submit",
    error: "Error",
    success: "Success",

    // Home Page
    heroTitle: "Digital Agriculture Companion",
    heroSubtitle: "Smart Kisan bridges traditional wisdom with modern AI. Leverage crop simulators, visual disease diagnostics, and trading pipelines to maximize your farm's potential.",
    trustedFarmers: "🌾 Trusted by 15,000+ Farmers",
    getStarted: "Get Started Free 🚀",
    loginCta: "Log In",
    downloadApp: "📲 Download App",
    impactFarmers: "Registered Farmers",
    impactAccuracy: "Diagnosis Accuracy",
    impactTraded: "Harvest Traded",
    impactFees: "Commission Fees",
    featureTitle: "Everything a Farmer Needs 🌱",
    featureSubtitle: "One platform, all your farming needs covered.",
    pwaCTA: "📱 Take Smart Kisan Everywhere",
    pwaDesc: "Install Smart Kisan as a native app on your device. Works offline, loads instantly, no app store needed!",
    pwaStep1Title: "Tap Install App",
    pwaStep1Desc: "Click the button below",
    pwaStep2Title: "Confirm Install",
    pwaStep2Desc: "Browser shows a prompt",
    pwaStep3Title: "Launch from Home Screen",
    pwaStep3Desc: "Opens like a native app!",
    downloadFree: "📲 Download App — Free",
    installedSuccess: "✅ Smart Kisan is installed on your device!",

    // Interactive Crop Planner
    cropPlanner: "🌱 Interactive Crop Planner",
    cropPlannerDesc: "Select a crop and sowing date to preview your growth schedule!",
    selectCrop: "Select Crop",
    sowingDate: "Estimated Sowing Date",
    simulateButton: "Simulate Growth Timeline 📈",
    pipelinePreview: "Growth Pipeline Preview",
    pipelineConfigureDesc: "Configure parameters on the left and simulate to view growth steps.",
    milestonesTitle: "Sowing Milestones:",
    enterCustomCrop: "Enter Custom Crop Name",

    // Login Page
    welcomeBack: "Welcome Back",
    loginSubtitle: "Log in to manage your fields and access agricultural insights.",
    emailAddress: "Email Address",
    password: "Password",
    forgotPassword: "Forgot Password?",
    loginButton: "Log In Securely 🚀",
    newToKisan: "New to Smart Kisan?",
    createAccountLink: "Create an account",
    demoLogins: "🔑 Quick Trial demo logins",
    demoFarmer: "🌾 Demo Farmer",
    demoMerchant: "🛒 Demo Merchant",
    singleClickLogin: "Single-click login",
    resetPassword: "Reset Password",
    resetSubtitle: "Enter your email address to request a password reset verification code.",
    sendOTP: "Send Verification OTP 🔑",
    backToLogin: "Back to Login",
    newPasswordWizard: "New Password Wizard",
    resetCodeLabel: "6-Digit Reset Code (OTP)",
    enterNewPassword: "Enter New Password",
    submitNewPassword: "Submit & Reset Password 🔐",
    requestNewResetCode: "Request New Reset Code",
    minCharacters: "Minimum 6 characters",

    // Register Page
    createAccount: "Create Account",
    registerSubtitle: "Register to set up your agricultural dashboard profile.",
    selectUserRole: "Select User Role",
    farmerRole: "Farmer",
    farmerDesc: "Cultivate & Sell",
    merchantRole: "Merchant",
    merchantDesc: "Trade & Purchase",
    fullName: "Full Name",
    registerBtn: "Register & Start Dashboard 🚀",
    alreadyHaveAccount: "Already have an account?",

    // Crop Recommendations
    recommendationTitle: "AI Crop Recommendation Engine",
    recommendationSubtitle: "Input your soil properties and location parameters to predict optimal crop varieties and resource allocation.",
    soilLocationDetails: "🧪 Soil & Location Details",
    soilType: "Soil Type",
    soilLoamy: "Loamy Soil",
    soilSandy: "Sandy Soil",
    soilClay: "Clayey Soil",
    soilBlack: "Black Soil",
    soilRed: "Red Soil",
    season: "Season",
    seasonKharif: "Kharif (Monsoon)",
    seasonRabi: "Rabi (Winter)",
    seasonZaid: "Zaid (Summer)",
    regionState: "Region / State",
    gpsDetectBtn: "📍 GPS",
    irrigationLabel: "Irrigation/Water Supply Available",
    soilChemistry: "⚙️ Soil Chemistry (NPK & pH)",
    soilPH: "Soil pH",
    acidic: "Acidic (4.0)",
    neutral: "Neutral (7.0)",
    alkaline: "Alkaline (9.0)",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    generateRecommendations: "Generate AI Recommendations",
    detectedWeather: "Detected Location & Weather",
    matchPercentage: "Match",
    estProfit: "Est. Profit",
    estProfitLabel: "Est. Profit",
    yieldLabel: "Yield:",
    waterLabel: "Water:",
    demandLabel: "Demand:",
    fertilizerActionPlan: "Fertilizer & Action Plan for",
    stepCalendar: "Step-by-Step Calendar",

    // AI Center / Diagnostics
    agriCenterTitle: "AI Agri-Center",
    agriCenterSubtitle: "Access cutting-edge advisory tools including visual disease checking, water managers, soil NPK prescription tools, and dynamic crop planners.",
    leafDiagnostics: "Leaf Disease Diagnostics",
    leafDiagnosticsDesc: "Snap or upload a photo of the affected plant leaf. Our AI model examines textures and spotting to suggest treatments.",
    cropTypeHint: "Crop Type Hint",
    dragDropPhoto: "Click here or drag-and-drop crop photo",
    supportsFormats: "Supports PNG, JPG, JPEG",
    analyzeImageBtn: "Analyze Image 🔬",
    diagnosticsReport: "AI Diagnostic Report",
    printPrescription: "🖨️ Print Prescription",
    uploadPrompt: "Upload a leaf photo and click analyze to output report.",
    modelConfidence: "AI Model Confidence",
    basedOnFoliage: "Based on visual foliage index patterns",
    cropTarget: "Crop Target:",
    detectedDisease: "Detected Disease:",
    severityLevel: "Threat Severity Level:",
    severityThreat: "Severity Threat",
    healthyLeafRef: "Reference Healthy Leaf:",
    organicRemedy: "Organic Remedy (Recommended)",
    chemicalControl: "Chemical Control",
    organicPrescription: "Organic Prescription:",
    chemicalGuidelines: "Chemical Treatment Guidelines:",

    // Kisan Bazaar
    bazaarTitle: "Kisan Bazaar",
    bazaarSubtitle: "Trade premium seeds, specialized tools, bio-fertilizers, or sell your own farm harvest directly to other farmers and wholesale merchants.",
    onlineSellTitle: "Sell Your Crop Online",
    onlineSellDesc: "List your crop, quality grade, asking price, and contact details to sell directly to verified wholesale buyers.",
    bazaarSellerCenter: "🚜 Seller Center",
    bazaarBrowse: "🛒 Browse Bazaar",
    bazaarCart: "🛒 Cart",
    bazaarFilterCategory: "Filter by Category",
    bazaarSearchPlaceholder: "Search products, categories, sellers...",
    bazaarSortPopularity: "Popularity",
    bazaarSortRating: "Highest Rated",
    bazaarSortPriceLow: "Price: Low to High",
    bazaarSortPriceHigh: "Price: High to Low",
    bazaarListSurplus: "📢 List Surplus to Sell",
    bazaarCloseForm: "Close Listing Form ✖",
    bazaarLoginToSell: "🔐 Login to sell your items",
    bazaarListHarvestTitle: "List Your Agriculture Item",
    bazaarListHarvestDesc: "Set your wholesale pricing, select category, upload or choose an image, and submit. Your listing appears instantly in the Bazaar catalog.",
    bazaarItemName: "Item / Crop Name *",
    bazaarCategory: "Category",
    bazaarSaleUnit: "Sale Unit *",
    bazaarWholesalePrice: "Wholesale Price (₹) *",
    bazaarSeedsGermination: "Germination Rate (%)",
    bazaarFertilizersRatio: "NPK Formula Ratio",
    bazaarProduceHarvestDate: "Harvest Date",
    bazaarItemDesc: "Item Description",
    bazaarPhotoPreset: "Choose Photo Preset (Or enter URL below)",
    bazaarUploadImage: "Upload Product Image (Recommended)",
    bazaarUploadingImage: "⏳ Uploading photo to server...",
    bazaarCustomImageUrl: "Or enter Custom Image URL...",
    bazaarPublishListing: "Publish Listing in Bazaar 🚀",
    bazaarPublishing: "Publishing listing...",
    bazaarLoadingInventory: "Loading Bazaar Inventory...",
    bazaarNoProductsMatched: "No products matched your filters.",
    bazaarTryClearing: "Try clearing search queries or checking other categories.",
    bazaarFarmerDirect: "👨‍🌾 Farmer Direct",
    bazaarMandiRef: "Mandi Ref",
    bazaarAddToCart: "+ Add 🛒",
    bazaarActiveListings: "Active Listings",
    bazaarAvailableItems: "Available Items",
    bazaarEstValue: "Est. Value (25 units sold)",
    bazaarOrderSuccessful: "Order placed successfully! Verified by Kisan SMS network.",
    bazaarCheckoutBtn: "Proceed to Checkout",
    bazaarOrderPlaced: "Order Placed!",
    bazaarOrderId: "Order ID:",
    bazaarCartEmpty: "Your cart is empty.",
    bazaarCloseBtn: "Close",

    // Mandi Prices
    mandiTitle: "Live Mandi Prices",
    mandiSubtitle: "Real-time agricultural commodity prices from 15+ APMC mandis across India.",
    pwaAndroidHint: "Android Chrome: Menu → 'Add to Home screen'",
    mandiSearchPlaceholder: "Search crop...",
    mandiAllCommodities: "All Commodities",
    mandiMinPrice: "Min Price",
    mandiAvgPrice: "Avg Price",
    mandiMaxPrice: "Max Price",
    mandiPriceSpread: "Price Spread",
    mandiTotalArrivals: "Total Arrivals",
    mandiTrend: "30-Day Trend",
    mandiBestBuy: "Best Buy Mandi",
    mandiBestSell: "Best Sell Mandi",
    mandiAutoRefresh: "Auto Refresh",
    mandiLastUpdate: "Last Update",
    mandiRefreshBtn: "🔄 Refresh",
    mandiWatchBtn: "☆ Watch",
    mandiWatchingBtn: "⭐ Watching",
    mandiSortLabel: "Sort By:",
    mandiArrivalTons: "Arrivals (Tons)",
    mandiMspBannerTitle: "Minimum Support Price (MSP)",
    mandiMspBannerDesc: "Government guaranteed MSP. If market prices fall below MSP, sell to government procurement agencies to protect your income.",
    mandiForecastTitle: "📊 Price Prediction Forecast (Next 7-30 Days)",
    mandiForecastDesc: "AI-powered commodity arrivals analysis and regional weather correlation.",
    mandiForecastSelect: "Forecast Period",
    mandiForecastBtn: "Analyze Forecast Trend 🔍",
    mandiForecastResult: "Prediction Result",
    mandiForecastSentiment: "Market Sentiment:",
    mandiForecastAdvise: "Actionable Advisory:",
    mandiForecastExpected: "Expected Price Range:",

    // Community Forum / Resources Hub
    communityResourcesTitle: "Community Resource Center & Advisories",
    communityResourcesSubtitle: "Community Advisory Board & Officer Directory",
    communityDirectoryTitle: "District Agronomist & Officer Directory",
    communityOfficerName: "Name",
    communityOfficerRole: "Designation / Role",
    communityOfficerContact: "Contact Number",
    communityOfficerRegion: "District / Region",
    communityMeetingsTitle: "📅 Upcoming Community Training & Webinars",
    communityMeetingsDesc: "Participate in live agricultural sessions hosted by agronomists.",
    communityMeetingTitle: "Topic",
    communityMeetingDate: "Date & Time",
    communityMeetingLink: "Action",
    communityMeetingJoin: "Join Session 🎥",
    communitySchemesTitle: "🏛️ Useful Government Portals & Crop Insurance Schemes",
    communitySchemesDesc: "Direct links to support and subsidy portals."
  },
  mr: {
    // Navbar
    title: "स्मार्ट किसान",
    home: "मुख्यपृष्ठ",
    dashboard: "डॅशबोर्ड",
    chat: "🤖 गप्पा",
    aiCenter: "🛠️ कृषी केंद्र",
    bazaar: "🛒 बाजार",
    community: "👥 समुदाय",
    weather: "☀️ हवामान",
    mandiPrices: "📈 बाजार भाव",
    recommendations: "🌱 पीक सल्लागार",
    learning: "📚 कृषी शिक्षण",
    login: "लॉगिन",
    register: "नोंदणी",
    logout: "बाहेर पडा",
    hi: "नमस्कार",
    installApp: "📲 ॲप डाउनलोड करा",

    // Common Button/Status
    loading: "लोड होत आहे...",
    submit: "सबमिट करा",
    error: "त्रुटी",
    success: "यशस्वी",

    // Home Page
    heroTitle: "डिजिटल कृषी साथीदार",
    heroSubtitle: "स्मार्ट किसान पारंपारिक ज्ञान आणि आधुनिक कृत्रिम बुद्धिमत्ता (AI) जोडतो. पीक सिम्युलेटर, रोग तपासणी आणि व्यापारी माध्यमांचा वापर करून नफा वाढवा.",
    trustedFarmers: "🌾 १५,०००+ शेतकऱ्यांचा विश्वास",
    getStarted: "विनामूल्य सुरू करा 🚀",
    loginCta: "लॉगिन करा",
    downloadApp: "📲 ॲप डाउनलोड करा",
    impactFarmers: "नोंदणीकृत शेतकरी",
    impactAccuracy: "निदान अचूकता",
    impactTraded: "व्यापार झालेले पीक",
    impactFees: "मध्यस्थी शुल्क",
    featureTitle: "शेतकऱ्यांच्या गरजेच्या सर्व गोष्टी 🌱",
    featureSubtitle: "एकच व्यासपीठ, तुमच्या सर्व गरजा पूर्ण करणारे.",
    pwaCTA: "📱 स्मार्ट किसान सर्वत्र न्या",
    pwaDesc: "स्मार्ट किसान ॲप तुमच्या मोबाईल डिव्हाइसवर डाउनलोड करा. ऑफलाइन वापरता येते आणि त्वरित उघडते!",
    pwaStep1Title: "ॲप डाउनलोड करा वर क्लिक करा",
    pwaStep1Desc: "खालील बटणावर क्लिक करा",
    pwaStep2Title: "डाउनलोडची पुष्टी करा",
    pwaStep2Desc: "ब्राउझरवर सूचना येईल",
    pwaStep3Title: "होम स्क्रीनवरून सुरू करा",
    pwaStep3Desc: "नेटीव्ह ॲपसारखे उघडेल!",
    downloadFree: "📲 ॲप डाउनलोड करा — विनामूल्य",
    installedSuccess: "✅ स्मार्ट किसान तुमच्या डिव्हाइसवर स्थापित आहे!",

    // Interactive Crop Planner
    cropPlanner: "🌱 परस्परसंवादी पीक नियोजक",
    cropPlannerDesc: "तुमच्या पीक वाढीचे वेळापत्रक पाहण्यासाठी पीक आणि पेरणीची तारीख निवडा!",
    selectCrop: "पीक निवडा",
    sowingDate: "पेरणीची अंदाजे तारीख",
    simulateButton: "वाढीचे वेळापत्रक पहा 📈",
    pipelinePreview: "पीक वाढीचे वेळापत्रक",
    pipelineConfigureDesc: "डावीकडील माहिती निवडून वेळापत्रक तयार करा.",
    milestonesTitle: "पेरणीचे टप्पे:",
    enterCustomCrop: "पिकाचे नाव टाका",

    // Crop names
    Tomato: "टोमॅटो",
    Paddy: "धान्य (भात)",
    Wheat: "गहू",
    Potato: "बटाटा",
    Mustard: "मोहरी",
    Chilli: "मिरची",
    Cotton: "कापूस",

    // Sowing Milestone Calendar UI
    sowingMilestoneCalendar: "पेरणीचे टप्पे वेळापत्रक",
    sowingCalendarDesc: "प्रगतीचा मागोवा घेण्यासाठी आणि स्वयंचलित वेळापत्रक तयार करण्यासाठी पिकांच्या पेरणीची/लागवडीची तारीख सेट करा.",
    yourActiveCalendars: "तुमचे सक्रिय वेळापत्रक",
    noActiveCalendars: "कोणतेही सक्रिय पीक वेळापत्रक सापडले नाही.",
    loginRequiredCalendar: "डेटाबेसमध्ये वेळापत्रक तयार करण्यासाठी आणि जतन करण्यासाठी लॉगिन करा.",
    selectCalendarPrompt: "टप्प्यांचा मागोवा घेण्यासाठी पीक वेळापत्रक निवडा किंवा तयार करा.",
    lifecycleTimeline: "वाढ चक्र वेळापत्रक",
    sowingLabel: "पेरणीची तारीख",
    activeStageLabel: "सक्रिय टप्पा",
    daysElapsedLabel: "पीक चक्राचा दिवस",
    addCustomMilestone: "नवीन टप्पा जोडा",
    dayOffsetPlaceholder: "दिवस अंतर",
    addBtn: "जोडा",
    customTaskLabel: "स्वतःचे काम",
    dueLabel: "देय तारीख",

    // Lifecycle Stages
    Nursery: "रोपवाटिका",
    Vegetative: "शाकीय वाढ (वाढीचा टप्पा)",
    Flowering: "फुलोरा अवस्था",
    Harvest: "काढणी",
    Tillering: "फुटवा अवस्था",
    Germination: "अंकुरण अवस्था",
    Jointing: "कांडी धरण्याची अवस्था",
    Sowing: "पेरणी",
    Reproductive: "पुनरुत्पादक अवस्था",

    // Home Previews Titles
    "Sowing in Nursery Bed": "रोपवाटिकेत पेरणी",
    "Transplanting Seedlings": "रोपांची पुनर्लागवड",
    "Top Dressing (NPK)": "खत मात्रा (NPK)",
    "Fruiting & Harvesting": "फळधारणा आणि काढणी",
    "Seed Soaking & Sprouting": "बियाणे भिजवणे आणि अंकुरण",
    "Seedling Nursery Pulling": "रोपवाटिका रोपे काढणे",
    "Tillering Phase Weeding": "फुटव्याच्या अवस्थेत खुरपणी",
    "Harvesting Paddy Crops": "धान्य / भात पिकाची काढणी",
    "Seed Treatment & Sowing": "बीजप्रक्रिया आणि पेरणी",
    "First Crown Root Irrigation": "पहिले सिंचन (मुकुट मूळ अवस्था)",
    "Tillering Phase Top Dressing": "फुटव्याच्या अवस्थेत खत मात्रा",
    "Maturity & Combines Harvesting": "पक्वता आणि काढणी",

    // Home Previews Details
    "Prepare fine soil bed and sow seeds 0.5 cm deep.": "मातीचा चांगला वाफा तयार करा आणि बियाणे ०.५ सेमी खोलीवर पेरा.",
    "Shift healthy seedlings to the main field with proper row spacing.": "योग्य अंतरावर निरोगी रोपे मुख्य शेतात पुनर्लागवड करा.",
    "Apply targeted nitrogen and potassium fertilizers around root zones.": "मुळांच्या जवळ योग्य प्रमाणात नायट्रोजन आणि पोटॅशियम खते द्या.",
    "Begin harvesting firm, ripe red tomatoes.": "पक्के, लाल आणि पिकलेले टोमॅटो काढण्यास सुरवात करा.",
    "Soak paddy seeds for 24 hours to accelerate sprouting.": "अंकुर वाढवण्यासाठी भाताचे बियाणे २४ तास पाण्यात भिजत ठेवा.",
    "Uproot nursery seedlings and transplant into puddled clay fields.": "रोपवाटिकेतील रोपे उपटून चिखल केलेल्या शेतात पुनर्लागवड करा.",
    "Ensure standing water depth of 5cm; clean out weeds.": "शेतात ५ सेमी पाणी साठवून ठेवा; तण काढून टाका.",
    "Drain the fields 10 days before harvesting dry golden grains.": "सोनेरी कोरडे दाणे काढण्यापूर्वी १० दिवस आधी शेतातील पाणी काढून टाका.",
    "Treat seeds and sow in rows spaced at 22 cm.": "बियाण्यांवर बीजप्रक्रिया करा आणि २२ सेमी अंतरावर ओळीत पेरणी करा.",
    "Irrigate the field - critical crown root initiation phase.": "शेताला पाणी द्या - मुकुट मूळ येण्याची ही अत्यंत महत्त्वाची अवस्था आहे.",
    "Apply Urea fertilizer to boost tillers density.": "फुटव्यांची संख्या वाढवण्यासाठी युरिया खताचा वापर करा.",
    "Harvest mature dry wheat heads.": "तयार झालेले सुके गव्हाचे कणीस कापून काढणी करा.",

    // Sowing Milestones (cropCalendarRoutes.js templates)
    // Tomato / Chilli
    "Nursery Sowing": "रोपवाटिका पेरणी",
    "Nursery Weeding & Thinning": "रोपवाटिका खुरपणी आणि विरळणी",
    "Transplanting Seedlings to Main Field": "मुख्य शेतात रोपांची पुनर्लागवड",
    "First Top Dressing (Apply NPK + Weeding)": "पहिली वरखत मात्रा - NPK + खुरपणी",
    "Staking & Trellising Tomato Vines": "टोमॅटो वेलींना आधार देणे आणि बांधणी",
    "Fruiting Spray (Micronutrients / Boron)": "फळधारणेसाठी मायक्रोन्युट्रिएंट्स / बोरॉन फवारणी",
    "First Harvest of Ripe Tomatoes": "टोमॅटोची पहिली काढणी",
    // Paddy
    "Seed Treatment & Nursery Bed Preparation": "बीजप्रक्रिया आणि रोपवाटिका तयार करणे",
    "Pulling Seedlings & Transplanting": "रोपे काढणे आणि पुनर्लागवड",
    "First Tillering Phase Fertilizer (Urea)": "पहिली फुटवा अवस्था खत मात्रा (युरिया)",
    "Mid-Tillering Weeding & Water Management": "मध्य-फुटवा खुरपणी आणि पाणी व्यवस्थापन",
    "Panicle Initiation Top Dressing (NPK)": "लोंबी येण्याच्या अवस्थेत खत मात्रा (NPK)",
    "Drain Field Prior to Harvest": "काढणीपूर्वी शेतातील पाणी काढून घेणे",
    "Harvesting & Threshing": "काढणी आणि मळणी",
    // Wheat
    "Field Preparation & Basal Fertilizer sowing": "शेत तयारी आणि पायाभूत खत पेरणी",
    "First Irrigation (Crown Root Initiation stage)": "पहिले सिंचन (मुकुट मूळ अवस्था)",
    "First Top Dressing (Urea Application)": "पहिली खत मात्रा (युरिया वापर)",
    "Second Irrigation & Hand Weeding": "दुसरे सिंचन आणि खुरपणी",
    "Jointing Stage Irrigation": "कांडी धरण्याच्या अवस्थेत सिंचन",
    "Flowering & Grain Filling Irrigation": "फुलोरा आणि दाणे भरण्याच्या अवस्थेत सिंचन",
    "Crop Maturity Drying & Harvesting": "पीक पक्वता आणि काढणी",
    // Potato
    "Planting Sprouted Seed Tubers": "अंकुरित बटाटा बेणे लागवड",
    "First Earthing Up & Fertilizer application": "पहिली भर देणे (वरंबा करणे) आणि खत मात्रा",
    "Tuber Initiation Stage Irrigation": "बटाटा तयार होण्याच्या सुरुवातीच्या अवस्थेत सिंचन",
    "Second Earthing Up & Weeding": "दुसरी भर देणे आणि खुरपणी",
    "Late Blight Disease Check & Spray": "लेट ब्लाइट (तांबेरा) रोग तपासणी आणि फवारणी",
    "Haulm Cutting (Dehalming)": "झाडाचा पाला कापणे (डीहॉलमिंग)",
    "Harvesting & Curing Tubers": "बटाटे काढणे आणि सुकवणे",
    // Mustard
    "Land Prep & Sowing Seeds": "जमीन तयारी आणि बियाणे पेरणी",
    "First Irrigation & Weeding": "पहिले सिंचन आणि खुरपणी",
    "Nitrogen Fertilizer Top Dressing": "नायट्रोजन खत मात्रा",
    "Thinning & Flowering Stage Water management": "विरळणी आणि फुलोऱ्याच्या अवस्थेत पाणी व्यवस्थापन",
    "Pod Formation (Siliqua stage) Pest check": "शेंगा धरण्याच्या अवस्थेत कीड तपासणी",
    // Chilli (remaining)
    "Seedling Transplanting": "रोपांची पुनर्लागवड",
    "First Weeding & Earthing Up": "पहिली खुरपणी आणि भर देणे",
    "First Top Dressing (NPK)": "पहिली खत मात्रा (NPK)",
    "Flowering & Fruiting Spray (Boron)": "फुलोरा आणि फळधारणा फवारणी (बोरॉन)",
    "First Picking of Green Chilli": "हिरव्या मिरचीची पहिली तोडणी",
    "Multiple Pickings & Liquid Manure boost": "वारंवार तोडणी आणि द्रवरूप खतांचा डोस",
    // Cotton
    "Field Prep & Sowing Cotton Seeds": "शेत तयारी आणि कापूस बियाणे पेरणी",
    "Thinning & Gap Filling": "विरळणी आणि नांगे भरणे",
    "First Hand Weeding & Interculture": "पहिली हात खुरपणी आणि कोळपणी",
    "Square Formation (Buds stage) NPK Spray": "पाती धरण्याच्या अवस्थेत (बोंड पूर्व अवस्था) NPK फवारणी",
    "Flowering & Boll Development Pest check": "फुलोरा आणि बोंड विकासाच्या अवस्थेत कीड तपासणी",
    "First Cotton Picking": "कापसाची पहिली वेचणी",
    "Final Picking & Cotton stalks clearance": "अंतिम वेचणी आणि कापूस पऱ्हाट्या काढणे",

    // Login Page
    welcomeBack: "पुन्हा स्वागत आहे",
    loginSubtitle: "तुमची शेती व्यवस्थापित करण्यासाठी आणि कृषी माहिती मिळवण्यासाठी लॉगिन करा.",
    emailAddress: "ईमेल पत्ता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड विसरलात?",
    loginButton: "सुरक्षित लॉगिन 🚀",
    newToKisan: "स्मार्ट किसानवर नवीन आहात?",
    createAccountLink: "नवीन खाते तयार करा",
    demoLogins: "🔑 चाचणी लॉगिन (Demo Logins)",
    demoFarmer: "🌾 शेतकरी लॉगिन (Demo)",
    demoMerchant: "🛒 व्यापारी लॉगिन (Demo)",
    singleClickLogin: "एक-क्लिक लॉगिन",
    resetPassword: "पासवर्ड रिसेट करा",
    resetSubtitle: "व्हेरिफिकेशन कोड (OTP) मिळवण्यासाठी तुमचा नोंदणीकृत ईमेल टाका.",
    sendOTP: "व्हेरिफिकेशन कोड (OTP) पाठवा 🔑",
    backToLogin: "लॉगिनवर जा",
    newPasswordWizard: "नवीन पासवर्ड तयार करा",
    resetCodeLabel: "६-अंकी रिसेट कोड (OTP)",
    enterNewPassword: "नवीन पासवर्ड टाका",
    submitNewPassword: "पासवर्ड बदला आणि सबमिट करा 🔐",
    requestNewResetCode: "नवीन रिसेट कोड मागवा",
    minCharacters: "किमान ६ अक्षरे",

    // Register Page
    createAccount: "खाते तयार करा",
    registerSubtitle: "तुमचा कृषी डॅशबोर्ड प्रोफाइल तयार करण्यासाठी नोंदणी करा.",
    selectUserRole: "वापरकर्ता भूमिका निवडा",
    farmerRole: "शेतकरी",
    farmerDesc: "लागवड आणि विक्री",
    merchantRole: "व्यापारी",
    merchantDesc: "खरेदी आणि व्यापार",
    fullName: "पूर्ण नाव",
    registerBtn: "नोंदणी करा आणि डॅशबोर्ड सुरू करा 🚀",
    alreadyHaveAccount: "आधीच खाते आहे का?",

    // Crop Recommendations
    recommendationTitle: "AI पीक शिफारस यंत्रणा",
    recommendationSubtitle: "तुमच्या शेतीसाठी योग्य पीक आणि संसाधनांचे नियोजन करण्यासाठी जमीन आणि हवामानाची माहिती टाका.",
    soilLocationDetails: "🧪 माती आणि ठिकाणाचे तपशील",
    soilType: "मातीचा प्रकार",
    soilLoamy: "गाळाची/लोमी माती",
    soilSandy: "वाळूमय माती",
    soilClay: "चिकणमाती",
    soilBlack: "काळी कसदार माती",
    soilRed: "तांबडी माती",
    season: "हंगाम",
    seasonKharif: "खरीप (पावसाळी)",
    seasonRabi: "रब्बी (हिवाळी)",
    seasonZaid: "उन्हाळी (उन्हाळी)",
    regionState: "प्रदेश / राज्य",
    gpsDetectBtn: "📍 जीपीएस",
    irrigationLabel: "सिंचन/पाण्याची उपलब्धता आहे",
    soilChemistry: "⚙️ मातीतील घटक (NPK आणि pH)",
    soilPH: "मातीचा पीएच (pH)",
    acidic: "आम्लधर्मी (4.0)",
    neutral: "उदासीन (7.0)",
    alkaline: "अल्कलीधर्मी (9.0)",
    nitrogen: "नायट्रोजन (N)",
    phosphorus: "फॉस्फरस (P)",
    potassium: "पोटॅश (K)",
    generateRecommendations: "पीक शिफारसी मिळवा",
    detectedWeather: "शोधलेले ठिकाण आणि हवामान",
    matchPercentage: "जुळणारे",
    estProfit: "अंदाजे नफा",
    estProfitLabel: "अंदाजे नफा",
    yieldLabel: "उत्पादन:",
    waterLabel: "पाणी:",
    demandLabel: "मागणी:",
    fertilizerActionPlan: "खत आणि कृती योजना:",
    stepCalendar: "टप्प्याटप्प्याने दिनदर्शिका",

    // AI Center / Diagnostics
    agriCenterTitle: "कृषी एआय केंद्र",
    agriCenterSubtitle: "पीक रोग तपासणी, पाणी व्यवस्थापन, मातीचे NPK खत नियोजन आणि पीक नियोजक यांसारख्या आधुनिक साधनांचा वापर करा.",
    leafDiagnostics: "पीक रोग निदान",
    leafDiagnosticsDesc: "पिकाच्या रोगाचे निदान करण्यासाठी रोगट पानाचा फोटो अपलोड करा. आमचे एआय मॉडेल लगेच उपाय सुचवेल.",
    cropTypeHint: "पिकाचा प्रकार",
    dragDropPhoto: "फोटो निवडा किंवा ड्रॅग करा",
    supportsFormats: "फक्त PNG, JPG, JPEG फॉरमॅट चालतील",
    analyzeImageBtn: "तपासा आणि निदान करा 🔬",
    diagnosticsReport: "एआय रोग निदान अहवाल",
    printPrescription: "🖨️ शिफारसी प्रिंट करा",
    uploadPrompt: "रोग निदान पाहण्यासाठी पानाचा फोटो अपलोड करा.",
    modelConfidence: "एआय मॉडेलची अचूकता",
    basedOnFoliage: "पानाच्या विविध घटकांच्या विश्लेषणावर आधारित",
    cropTarget: "निवडलेले पीक:",
    detectedDisease: "शोधलेला रोग:",
    severityLevel: "रोगाची तीव्रता:",
    severityThreat: "रोगाचा धोका",
    healthyLeafRef: "निरोगी पानाचा संदर्भ:",
    organicRemedy: "सेंद्रिय उपाय (शिफारस केलेले)",
    chemicalControl: "रासायनिक नियंत्रण",
    organicPrescription: "सेंद्रिय उपाय:",
    chemicalGuidelines: "रासायनिक उपचार मार्गदर्शक तत्वे:",

    // Kisan Bazaar
    bazaarTitle: "किसान बाजार",
    bazaarSubtitle: "उत्कृष्ट बियाणे, शेतीची साधने, जैविक खते खरेदी करा किंवा तुमचे स्वतःचे पीक थेट इतर शेतकऱ्यांना आणि व्यापाऱ्यांना विकून नफा मिळवा.",
    onlineSellTitle: "तुमचे पीक ऑनलाईन विका",
    onlineSellDesc: "तुमचे पीक, त्याची प्रत, किंमत आणि संपर्क तपशील टाकून थेट ऑनलाईन खरेदीदारांशी संपर्क साधा आणि माल विका.",
    bazaarSellerCenter: "🚜 विक्रेता केंद्र",
    bazaarBrowse: "🛒 बाजार पहा",
    bazaarCart: "🛒 कार्ट",
    bazaarFilterCategory: "श्रेणीनुसार फिल्टर करा",
    bazaarSearchPlaceholder: "उत्पादने, श्रेणी, विक्रेते शोधा...",
    bazaarSortPopularity: "लोकप्रियता",
    bazaarSortRating: "उच्च मानांकित",
    bazaarSortPriceLow: "किंमत: कमी ते जास्त",
    bazaarSortPriceHigh: "किंमत: जास्त ते कमी",
    bazaarListSurplus: "📢 पीक विक्रीसाठी नोंदवा",
    bazaarCloseForm: "फॉर्म बंद करा ✖",
    bazaarLoginToSell: "🔐 विक्री करण्यासाठी आधी लॉगिन करा",
    bazaarListHarvestTitle: "तुमच्या पिकाची/वस्तूची नोंदणी करा",
    bazaarListHarvestDesc: "तुमची घाऊक किंमत ठरवा, श्रेणी निवडा, फोटो अपलोड करा आणि सबमिट करा. तुमची नोंदणी बाजारात त्वरित दिसून येईल.",
    bazaarItemName: "वस्तू किंवा पिकाचे नाव *",
    bazaarCategory: "श्रेणी",
    bazaarSaleUnit: "विक्रीचे युनिट *",
    bazaarWholesalePrice: "घाऊक किंमत (₹) *",
    bazaarSeedsGermination: "बियाणे उगवण क्षमता (%)",
    bazaarFertilizersRatio: "NPK खत प्रमाण",
    bazaarProduceHarvestDate: "काढणीची तारीख",
    bazaarItemDesc: "वस्तूचे वर्णन",
    bazaarPhotoPreset: "फोटो निवडा (किंवा खाली URL टाका)",
    bazaarUploadImage: "उत्पादन फोटो अपलोड करा (शिफारस केलेले)",
    bazaarUploadingImage: "⏳ फोटो सर्व्हरवर अपलोड होत आहे...",
    bazaarCustomImageUrl: "किंवा कस्टम फोटो URL प्रविष्ट करा...",
    bazaarPublishListing: "बाझारमध्ये नोंदणी प्रकाशित करा 🚀",
    bazaarPublishing: "प्रकाशित होत आहे...",
    bazaarLoadingInventory: "बाजार यादी लोड होत आहे...",
    bazaarNoProductsMatched: "तुमच्या फिल्टरशी जुळणारे उत्पादन सापडले नाही.",
    bazaarTryClearing: "शोध संज्ञा बदला किंवा इतर श्रेणी तपासा.",
    bazaarFarmerDirect: "👨‍🌾 थेट शेतकरी",
    bazaarMandiRef: "बाजार भाव संदर्भ",
    bazaarAddToCart: "+ कार्टमध्ये जोडा 🛒",
    bazaarActiveListings: "सक्रिय यादी",
    bazaarAvailableItems: "उपलब्ध वस्तू",
    bazaarEstValue: "अंदाजे मूल्य (२५ युनिट्स विक्री)",
    bazaarOrderSuccessful: "ऑर्डर यशस्वीरित्या नोंदवली गेली! किसान एसएमएस नेटवर्कद्वारे व्हेरिफाय केली जाईल.",
    bazaarCheckoutBtn: "चेकआउट करा",
    bazaarOrderPlaced: "ऑर्डर पूर्ण झाली!",
    bazaarOrderId: "ऑर्डर आयडी:",
    bazaarCartEmpty: "तुमची कार्ट रिकामी आहे.",
    bazaarCloseBtn: "बंद करा",

    // Mandi Prices
    mandiTitle: "बाजार भाव",
    mandiSubtitle: "भारतातील १५+ कृषी उत्पन्न बाजार समित्यांमधील पिकांचे चालू बाजार भाव.",
    pwaAndroidHint: "अँड्रॉइड क्रोम: मेनू → 'होम स्क्रीनवर जोडा'",
    mandiSearchPlaceholder: "पीक शोधा...",
    mandiAllCommodities: "सर्व पिके",
    mandiMinPrice: "किमान किंमत",
    mandiAvgPrice: "अंदाजे किंमत",
    mandiMaxPrice: "कमाल किंमत",
    mandiPriceSpread: "किंमतीतील फरक",
    mandiTotalArrivals: "एकूण आवक",
    mandiTrend: "३०-दिवसांचा कल",
    mandiBestBuy: "स्वस्त खरेदी बाजार",
    mandiBestSell: "महाग विक्री बाजार",
    mandiAutoRefresh: "स्वयंचलित रीफ्रेश",
    mandiLastUpdate: "शेवटचे अपडेट",
    mandiRefreshBtn: "🔄 रीफ्रेश",
    mandiWatchBtn: "☆ वॉचलिस्ट",
    mandiWatchingBtn: "⭐ वॉचिंग",
    mandiSortLabel: "क्रमवारी लावा:",
    mandiArrivalTons: "आवक (टन)",
    mandiMspBannerTitle: "किमान आधारभूत किंमत (MSP)",
    mandiMspBannerDesc: "शासकीय आधारभूत हमीभाव. जर बाजारातील भाव हमीभावापेक्षा कमी असतील, तर संरक्षण मिळवण्यासाठी शासकीय खरेदी केंद्रांवर विक्री करा.",
    mandiForecastTitle: "📊 भावी बाजार भाव अंदाज (पुढील ७-३० दिवस)",
    mandiForecastDesc: "AI द्वारे पिकाची आवक आणि हवामानाचा अंदाज घेऊन बनवलेले विश्लेषण.",
    mandiForecastSelect: "अंदाजाचा कालावधी",
    mandiForecastBtn: "बाजार भाव अंदाज तपासा 🔍",
    mandiForecastResult: "अंदाजाचे निकाल",
    mandiForecastSentiment: "बाजार कल (Sentiment):",
    mandiForecastAdvise: "कृती सल्ला (Advisory):",
    mandiForecastExpected: "अपेक्षित बाजार भाव श्रेणी:",

    // Community Forum / Resources Hub
    communityResourcesTitle: "कृषी समुदाय संसाधन केंद्र व सल्ला",
    communityResourcesSubtitle: "सामुदायिक सल्लागार मंडळ आणि अधिकारी डिरेक्टरी",
    communityDirectoryTitle: "जिल्हा कृषी अधिकारी व सल्लागार डिरेक्टरी",
    communityOfficerName: "नाव",
    communityOfficerRole: "पद / भूमिका",
    communityOfficerContact: "संपर्क क्रमांक",
    communityOfficerRegion: "जिल्हा / तालुका",
    communityMeetingsTitle: "📅 आगामी शेतकरी प्रशिक्षण आणि वेबिनार वेळापत्रक",
    communityMeetingsDesc: "तज्ज्ञ कृषी अधिकाऱ्यांनी आयोजित केलेल्या थेट सत्रांमध्ये सहभागी व्हा.",
    communityMeetingTitle: "विषय",
    communityMeetingDate: "दिनांक आणि वेळ",
    communityMeetingLink: "कृती",
    communityMeetingJoin: "सत्रामध्ये सहभागी व्हा 🎥",
    communitySchemesTitle: "🏛️ उपयुक्त सरकारी योजना व पीक विमा पोर्टल्स",
    communitySchemesDesc: "थेट सरकारी मदत आणि अनुदान योजनांच्या लिंक्स."
  },
  hi: {
    // Navbar
    home: "मुख्यपृष्ठ",
    dashboard: "डैशबोर्ड",
    chat: "🤖 बातचीत",
    aiCenter: "🛠️ कृषि केंद्र",
    bazaar: "🛒 बाजार",
    community: "👥 समुदाय",
    weather: "☀️ मौसम",
    mandiPrices: "📈 मंडी भाव",
    recommendations: "🌱 फसल सलाहकार",
    learning: "📚 कृषि शिक्षण",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआऊट",
    hi: "नमस्ते",
    installApp: "📲 ऐप इंस्टॉल करें",

    // Common Button/Status
    loading: "लोड हो रहा है...",
    submit: "जमा करें",
    error: "त्रुटि",
    success: "सफलता",

    // Home Page
    heroTitle: "डिजिटल कृषि साथी",
    heroSubtitle: "स्मार्ट किसान पारंपरिक ज्ञान और आधुनिक एआई को जोड़ता है। अपने खेत की क्षमता को अधिकतम करने के लिए फसल सिमुलेटर, दृश्य रोग निदान और व्यापार पाइपलाइनों का लाभ उठाएं।",
    trustedFarmers: "🌾 15,000+ किसानों द्वारा विश्वसनीय",
    getStarted: "मुफ़्त शुरू करें 🚀",
    loginCta: "लॉग इन करें",
    downloadApp: "📲 ऐप डाउनलोड करें",
    impactFarmers: "पंजीकृत किसान",
    impactAccuracy: "निदान सटीकता",
    impactTraded: "व्यापार की गई फसल",
    impactFees: "दलाली शुल्क",
    featureTitle: "किसान की जरूरत का सब कुछ 🌱",
    featureSubtitle: "एक मंच, आपकी सभी कृषि आवश्यकताएं पूरी।",
    pwaCTA: "📱 स्मार्ट किसान को हर जगह ले जाएं",
    pwaDesc: "अपने डिवाइस पर स्मार्ट किसान को एक नेटिव ऐप के रूप में इंस्टॉल करें। ऑफ़लाइन काम करता है, तुरंत लोड होता है, किसी ऐप स्टोर की आवश्यकता नहीं है!",
    pwaStep1Title: "ऐप इंस्टॉल करें पर टैप करें",
    pwaStep1Desc: "नीचे दिए गए बटन पर क्लिक करें",
    pwaStep2Title: "इंस्टॉल की पुष्टि करें",
    pwaStep2Desc: "ब्राउज़र एक संकेत दिखाता है",
    pwaStep3Title: "होम स्क्रीन से लॉन्च करें",
    pwaStep3Desc: "एक नेटिव ऐप की तरह खुलता है!",
    downloadFree: "📲 ऐप डाउनलोड करें — मुफ़्त",
    installedSuccess: "✅ स्मार्ट किसान आपके डिवाइस पर इंस्टॉल है!",

    // Interactive Crop Planner
    cropPlanner: "🌱 इंटरएक्टिव फसल योजनाकार",
    cropPlannerDesc: "अपनी वृद्धि अनुसूची देखने के लिए एक फसल और बुवाई की तारीख चुनें!",
    selectCrop: "फसल चुनें",
    sowingDate: "बुवाई की अंदाजे तारीख",
    simulateButton: "वृद्धि समयरेखा अनुकरण करें 📈",
    pipelinePreview: "वृद्धि पाइपलाइन पूर्वावलोकन",
    pipelineConfigureDesc: "बाएं हिस्से में पैरामीटर कॉन्फ़िगर करें और वृद्धि चरणों को देखने के लिए अनुकरण करें।",
    milestonesTitle: "बुवाई के मील के पत्थर:",
    enterCustomCrop: "कस्टम फसल का नाम दर्ज करें",

    // Login Page
    welcomeBack: "आपका स्वागत है",
    loginSubtitle: "अपने खेतों का प्रबंधन करने और कृषि संबंधी जानकारी प्राप्त करने के लिए लॉग इन करें।",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    loginButton: "सुरक्षित रूप से लॉग इन करें 🚀",
    newToKisan: "स्मार्ट किसान पर नए हैं?",
    createAccountLink: "एक खाता बनाएं",
    demoLogins: "🔑 त्वरित परीक्षण डेमो लॉगिन",
    demoFarmer: "🌾 डेमो किसान",
    demoMerchant: "🛒 डेमो व्यापारी",
    singleClickLogin: "एक-क्लिक लॉगिन",
    resetPassword: "पासवर्ड रीसेट करें",
    resetSubtitle: "पासवर्ड रीसेट सत्यापन कोड का अनुरोध करने के लिए अपना ईमेल पता दर्ज करें।",
    sendOTP: "सत्यापन ओटीपी भेजें 🔑",
    backToLogin: "लॉगिन पर वापस जाएं",
    newPasswordWizard: "नया पासवर्ड विजार्ड",
    resetCodeLabel: "6-अंकीय रीसेट कोड (ओटीपी)",
    enterNewPassword: "नया पासवर्ड दर्ज करें",
    submitNewPassword: "जमा करें और पासवर्ड रीसेट करें 🔐",
    requestNewResetCode: "नया रीसेट कोड का अनुरोध करें",
    minCharacters: "कम से कम 6 अक्षर",

    // Register Page
    createAccount: "खाता बनाएं",
    registerSubtitle: "अपना कृषि डैशबोर्ड प्रोफ़ाइल सेट करने के लिए पंजीकरण करें।",
    selectUserRole: "उपयोगकर्ता भूमिका चुनें",
    farmerRole: "किसान",
    farmerDesc: "खेती करें और बेचें",
    merchantRole: "व्यापारी",
    merchantDesc: "व्यापार करें और खरीदें",
    fullName: "पूरा नाम",
    registerBtn: "पंजीकरण करें और डैशबोर्ड शुरू करें 🚀",
    alreadyHaveAccount: "पहले से ही खाता है?",

    // Crop Recommendations
    recommendationTitle: "AI फसल अनुशंसा इंजन",
    recommendationSubtitle: "अनुकुलतम फसल किस्मों और संसाधन आवंटन का अनुमान लगाने के लिए अपनी मिट्टी के गुणों और स्थान मापदंडों को दर्ज करें।",
    soilLocationDetails: "🧪 मिट्टी और स्थान विवरण",
    soilType: "मिट्टी का प्रकार",
    soilLoamy: "दोमट मिट्टी",
    soilSandy: "बलुई मिट्टी",
    soilClay: "चिकनी मिट्टी",
    soilBlack: "काली मिट्टी",
    soilRed: "लाल मिट्टी",
    season: "मौसम",
    seasonKharif: "खरीफ (मानसून)",
    seasonRabi: "रबी (सर्दियों)",
    seasonZaid: "जायद (गर्मी)",
    regionState: "क्षेत्र / राज्य",
    gpsDetectBtn: "📍 जीपीएस",
    irrigationLabel: "सिंचन/पानी की आपूर्ति उपलब्ध है",
    soilChemistry: "⚙️ मृदा रसायन (NPK और pH)",
    soilPH: "मिट्टी का पीएच",
    acidic: "अम्लीय (4.0)",
    neutral: "उदासीन (7.0)",
    alkaline: "क्षारीय (9.0)",
    nitrogen: "नाइट्रोजन (N)",
    phosphorus: "फास्फोरस (P)",
    potassium: "पोटेशियम (K)",
    generateRecommendations: "AI अनुशंसाएँ उत्पन्न करें",
    detectedWeather: "पता चला स्थान और मौसम",
    matchPercentage: "मेल",
    estProfit: "अनुमानित लाभ",
    estProfitLabel: "अनुमानित लाभ",
    yieldLabel: "उपज:",
    waterLabel: "पानी:",
    demandLabel: "मांग:",
    fertilizerActionPlan: "खाद और कार्य योजना:",
    stepCalendar: "चरण-दर-चरण कैलेंडर",

    // AI Center / Diagnostics
    agriCenterTitle: "कृषि एआई केंद्र",
    agriCenterSubtitle: "पीक रोग निदान, जल प्रबंधकों, मिट्टी के NPK खाद नियोजन और फसल नियोजक जैसे आधुनिक उपकरणों का उपयोग करें।",
    leafDiagnostics: "पत्ती रोग निदान",
    leafDiagnosticsDesc: "प्रभावित पौधे की पत्ती की तस्वीर लें या अपलोड करें। हमारा एआई मॉडल उपचार सुझाने के लिए बनावट और धब्बों की जांच करता है।",
    cropTypeHint: "फसल का प्रकार",
    dragDropPhoto: "तस्वीर चुनें या यहाँ खींचें",
    supportsFormats: "PNG, JPG, JPEG प्रारूपों का समर्थन करता है",
    analyzeImageBtn: "छवि का विश्लेषण करें 🔬",
    diagnosticsReport: "एआई रोग निदान रिपोर्ट",
    printPrescription: "🖨️ पर्चा प्रिंट करें",
    uploadPrompt: "रिपोर्ट देखने के लिए पत्ती की फोटो अपलोड करें और विश्लेषण करें पर क्लिक करें।",
    modelConfidence: "एआई मॉडल विश्वसनीयता",
    basedOnFoliage: "पत्ती के विभिन्न घटकों के विश्लेषण पर आधारित",
    cropTarget: "लक्षित फसल:",
    detectedDisease: "पता चला रोग:",
    severityLevel: "खतरे की गंभीरता का स्तर:",
    severityThreat: "गंभीरता खतरा",
    healthyLeafRef: "संदर्भ स्वस्थ पत्ती:",
    organicRemedy: "जैविक उपचार (अनुशंसित)",
    chemicalControl: "रासायनिक नियंत्रण",
    organicPrescription: "जैविक नुस्खा:",
    chemicalGuidelines: "रासायनिक उपचार दिशानिर्देश:",

    // Kisan Bazaar
    bazaarTitle: "किसान बाजार",
    bazaarSubtitle: "उत्कृष्ट बीज, विशेष उपकरण, जैविक खाद खरीदें या अपनी खुद की फसल सीधे अन्य किसानों और थोक व्यापारियों को बेचें।",
    onlineSellTitle: "अपनी फसल ऑनलाइन बेचें",
    onlineSellDesc: "सीधे सत्यापित थोक खरीदारों को बेचने के लिए अपनी फसल, गुणवत्ता ग्रेड, पूछी जा रही कीमत और संपर्क विवरण सूचीबद्ध करें।",
    bazaarSellerCenter: "🚜 विक्रेता केंद्र",
    bazaarBrowse: "🛒 बाजार ब्राउज़ करें",
    bazaarCart: "🛒 कार्ट",
    bazaarFilterCategory: "श्रेणी के अनुसार छानें",
    bazaarSearchPlaceholder: "उत्पाद, श्रेणियां, विक्रेता खोजें...",
    bazaarSortPopularity: "लोकप्रियता",
    bazaarSortRating: "उच्चतम रेटेड",
    bazaarSortPriceLow: "मूल्य: कम से उच्च",
    bazaarSortPriceHigh: "मूल्य: उच्च से कम",
    bazaarListSurplus: "📢 बेचने के लिए अधिशेष सूचीबद्ध करें",
    bazaarCloseForm: "लिस्टिंग फॉर्म बंद करें ✖",
    bazaarLoginToSell: "🔐 अपनी चीजें बेचने के लिए लॉग इन करें",
    bazaarListHarvestTitle: "अपनी कृषि वस्तु सूचीबद्ध करें",
    bazaarListHarvestDesc: "अपनी थोक मूल्य निर्धारण सेट करें, श्रेणी चुनें, फोटो अपलोड या चुनें, और सबमिट करें। आपकी लिस्टिंग तुरंत बाज़ार कैटलॉग में दिखाई देगी।",
    bazaarItemName: "वस्तु / फसल का नाम *",
    bazaarCategory: "श्रेणी",
    bazaarSaleUnit: "बिक्री इकाई *",
    bazaarWholesalePrice: "थोक मूल्य (₹) *",
    bazaarSeedsGermination: "अंकुरण दर (%)",
    bazaarFertilizersRatio: "NPK फॉर्मूला अनुपात",
    bazaarProduceHarvestDate: "कटाई की तिथि",
    bazaarItemDesc: "वस्तु विवरण",
    bazaarPhotoPreset: "फोटो प्रीसेट चुनें (या नीचे URL दर्ज करें)",
    bazaarUploadImage: "उत्पाद फोटो अपलोड करें (अनुशंसित)",
    bazaarUploadingImage: "⏳ फोटो सर्वर पर अपलोड हो रहा है...",
    bazaarCustomImageUrl: "या कस्टम फोटो URL दर्ज करें...",
    bazaarPublishListing: "बाजार में लिस्टिंग प्रकाशित करें 🚀",
    bazaarPublishing: "लिस्टिंग प्रकाशित की जा रही है...",
    bazaarLoadingInventory: "बाजार सूची लोड हो रही है...",
    bazaarNoProductsMatched: "आपके फिल्टर से कोई उत्पाद मेल नहीं खाता।",
    bazaarTryClearing: "खोज क्वेरी साफ़ करने का प्रयास करें या अन्य श्रेणियां देखें।",
    bazaarFarmerDirect: "👨‍🌾 किसान सीधे",
    bazaarMandiRef: "मंडी संदर्भ",
    bazaarAddToCart: "+ जोड़ें 🛒",
    bazaarActiveListings: "सक्रिय सूचियां",
    bazaarAvailableItems: "उपलब्ध वस्तुएं",
    bazaarEstValue: "अनुमानित मूल्य (25 इकाइयाँ बेची गईं)",
    bazaarOrderSuccessful: "ऑर्डर सफलतापूर्वक दिया गया! किसान एसएमएस नेटवर्क द्वारा सत्यापित।",
    bazaarCheckoutBtn: "चेकआउट के लिए आगे बढ़ें",
    bazaarOrderPlaced: "ऑर्डर दिया गया!",
    bazaarOrderId: "ऑर्डर आईडी:",
    bazaarCartEmpty: "आपकी कार्ट खाली है।",
    bazaarCloseBtn: "बंद करें",

    // Mandi Prices
    mandiTitle: "लाइव मंडी भाव",
    mandiSubtitle: "भारत भर की 15+ एपीएमसी मंडियों से वास्तविक समय में कृषि कमोडिटी की कीमतें।",
    pwaAndroidHint: "एंड्रॉइड क्रोम: मेनू → 'होम स्क्रीन पर जोड़ें'",
    mandiSearchPlaceholder: "फसल खोजें...",
    mandiAllCommodities: "सभी फसलें",
    mandiMinPrice: "न्यूनतम मूल्य",
    mandiAvgPrice: "औसत मूल्य",
    mandiMaxPrice: "अधिकतम मूल्य",
    mandiPriceSpread: "मूल्य अंतर",
    mandiTotalArrivals: "कुल आवक",
    mandiTrend: "30-दिवसीय प्रवृत्ति",
    mandiBestBuy: "सस्ती खरीद मंडी",
    mandiBestSell: "महंगी बिक्री मंडी",
    mandiAutoRefresh: "ऑटो रीफ्रेश",
    mandiLastUpdate: "अंतिम अपडेट",
    mandiRefreshBtn: "🔄 रीफ्रेश",
    mandiWatchBtn: "☆ वॉचलिस्ट",
    mandiWatchingBtn: "⭐ वॉचिंग",
    mandiSortLabel: "क्रमबद्ध करें:",
    mandiArrivalTons: "आवक (टन)",
    mandiMspBannerTitle: "न्यूनतम समर्थन मूल्य (MSP)",
    mandiMspBannerDesc: "सरकार द्वारा गारंटीकृत MSP। यदि बाजार की कीमतें MSP से नीचे गिरती हैं, तो अपनी आय की रक्षा के लिए सरकारी खरीद एजेंसियों को बेचें।",
    mandiForecastTitle: "📊 मूल्य भविष्यवाणी का पूर्वानुमान (अगले 7-30 दिन)",
    mandiForecastDesc: "एॉ-संचालित कमोडिटी आवक विश्लेषण और क्षेत्रीय मौसम सहसंबंध।",
    mandiForecastSelect: "पूर्वानुमान अवधि",
    mandiForecastBtn: "पूर्वानुमान प्रवृत्ति का विश्लेषण करें 🔍",
    mandiForecastResult: "भविष्यवाणी का परिणाम",
    mandiForecastSentiment: "बाजार का रुख:",
    mandiForecastAdvise: "कार्यवाही योग्य सलाह:",
    mandiForecastExpected: "expected price range:",

    // Community Forum / Resources Hub
    communityResourcesTitle: "सामुदायिक संसाधन केंद्र और सलाह",
    communityResourcesSubtitle: "सामुदायिक सलाहकार बोर्ड और अधिकारी निर्देशिका",
    communityDirectoryTitle: "जिला कृषि विज्ञानी और अधिकारी निर्देशिका",
    communityOfficerName: "नाम",
    communityOfficerRole: "पद / भूमिका",
    communityOfficerContact: "संपर्क नंबर",
    communityOfficerRegion: "जिला / क्षेत्र",
    communityMeetingsTitle: "📅 आगामी किसान प्रशिक्षण और वेबिनार",
    communityMeetingsDesc: "कृषि विज्ञानियों द्वारा आयोजित लाइव सत्रों में भाग लें।",
    communityMeetingTitle: "विषय",
    communityMeetingDate: "दिनांक और समय",
    communityMeetingLink: "कार्यवाही",
    communityMeetingJoin: "सत्र में शामिल हों 🎥",
    communitySchemesTitle: "🏛️ उपयोगी सरकारी पोर्टल और फसल बीमा योजनाएं",
    communitySchemesDesc: "सीधे सरकारी सहायता और सब्सिडी पोर्टल के लिंक।"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('sk-lang');
    return saved === 'mr' ? 'mr' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('sk-lang', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'en' ? 'mr' : 'en'));
  };

  const t = (key) => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;
